In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("healthcare_raw_data.csv")
df.head()

,Patient_ID,Age,Gender,Race,Height_cm,Weight_kg,BMI,Blood_Pressure,Cholesterol,Glucose,...,Medication_Count,Hospital_Visits_Last_Year,Insurance_Type,Income_Level,City,Admission_Date,Discharge_Date,Length_of_Stay,Total_Hospital_Cost,Readmitted_30_Days
0,P0001,72,Male,Black,174,92,30.4,148/92,241,132,...,6,4,Medicare,Low,Baltimore,2026-01-04,2026-01-11,7,"$14,220.50",Yes
1,P0002,29,female,White,165,61,22.4,118/76,176,91,...,0,0,Private,Medium,Boston,01/08/2026,01/10/2026,2,"$3,180.00",No
2,P0003,64,MALE,Hispanic,68,98,32.9,145/88,263,142,...,5,3,Medicaid,Low,New Yrok,2026-01-11,2026-01-18,7,"$13,750.75",Yes
3,P0004,45,Female,Asian,160,77,30.1,132/84,198,126,...,2,1,Private,Medium,Chicago,01/12/2026,01/16/2026,4,"$7,930.20",No
4,P0005,83,male,Black,171,88,30.1,156/95,255,151,...,8,5,Medicare,Low,Detroit,2026-01-15,2026-01-25,10,"$21,400.90",Yes

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Patient_ID                 50 non-null     object
 1   Age                        50 non-null     int64
 2   Gender                     50 non-null     object
 3   Race                       50 non-null     object
 4   Height_cm                  50 non-null     int64
 5   Weight_kg                  50 non-null     int64
 6   BMI                        50 non-null     float64
 7   Blood_Pressure             50 non-null     object
 8   Cholesterol                50 non-null     int64
 9   Glucose                    50 non-null     int64
 10  Heart_Rate                 50 non-null     int64
 11  Smoking_Status             50 non-null     object
 12  Alcohol_Use                30 non-null     object
 13  Exercise_Frequency         50 non-null     object
 14  Diabetes                   50 non-null     object
 15  Hypertension               50 non-null     object
 16  Heart_Disease              50 non-null     object
 17  Medication_Count           50 non-null     int64
 18  Hospital_Visits_Last_Year  50 non-null     int64
 19  Insurance_Type             50 non-null     object
 20  Income_Level               50 non-null     object
 21  City                       50 non-null     object
 22  Admission_Date             50 non-null     object
 23  Discharge_Date             50 non-null     object
 24  Length_of_Stay             50 non-null     int64
 25  Total_Hospital_Cost        50 non-null     object
 26  Readmitted_30_Days         50 non-null     object
dtypes: float64(1), int64(9), object(17)
memory usage: 10.7+ KB

In [3]:
df.describe()

,Age,Height_cm,Weight_kg,BMI,Cholesterol,Glucose,Heart_Rate,Medication_Count,Hospital_Visits_Last_Year,Length_of_Stay
count,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.00000,50.000000,50.000000,50.000000
mean,58.600000,147.600000,83.200000,29.180000,226.600000,128.400000,85.00000,4.200000,2.600000,6.000000
std,19.510332,40.499937,13.176974,3.585344,34.158096,20.766928,8.08122,2.885573,1.873554,2.784798
min,29.000000,68.000000,61.000000,22.400000,176.000000,91.000000,72.00000,0.000000,0.000000,2.000000
25%,45.000000,160.000000,77.000000,30.100000,198.000000,126.000000,80.00000,2.000000,1.000000,4.000000
50%,64.000000,165.000000,88.000000,30.100000,241.000000,132.000000,88.00000,5.000000,3.000000,7.000000
75%,72.000000,171.000000,92.000000,30.400000,255.000000,142.000000,91.00000,6.000000,4.000000,7.000000
max,83.000000,174.000000,98.000000,32.900000,263.000000,151.000000,94.00000,8.000000,5.000000,10.000000

In [5]:
df.shape

(50, 27)

In [6]:
df.isnull().sum()

Patient_ID                    0
Age                           0
Gender                        0
Race                          0
Height_cm                     0
Weight_kg                     0
BMI                           0
Blood_Pressure                0
Cholesterol                   0
Glucose                       0
Heart_Rate                    0
Smoking_Status                0
Alcohol_Use                  20
Exercise_Frequency            0
Diabetes                      0
Hypertension                  0
Heart_Disease                 0
Medication_Count              0
Hospital_Visits_Last_Year     0
Insurance_Type                0
Income_Level                  0
City                          0
Admission_Date                0
Discharge_Date                0
Length_of_Stay                0
Total_Hospital_Cost           0
Readmitted_30_Days            0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [10]:
df["Alcohol_Use"] = df["Alcohol_Use"].fillna("Unknown")

In [11]:
df["Alcohol_Use"].isnull().sum()

np.int64(0)

In [12]:
df.isnull().sum()

Patient_ID                   0
Age                          0
Gender                       0
Race                         0
Height_cm                    0
Weight_kg                    0
BMI                          0
Blood_Pressure               0
Cholesterol                  0
Glucose                      0
Heart_Rate                   0
Smoking_Status               0
Alcohol_Use                  0
Exercise_Frequency           0
Diabetes                     0
Hypertension                 0
Heart_Disease                0
Medication_Count             0
Hospital_Visits_Last_Year    0
Insurance_Type               0
Income_Level                 0
City                         0
Admission_Date               0
Discharge_Date               0
Length_of_Stay               0
Total_Hospital_Cost          0
Readmitted_30_Days           0
dtype: int64

In [14]:
 df["Admission_Date"] = pd.to_datetime(df["Admission_Date"], format='mixed' )

,Patient_ID,Age,Gender,Race,Height_cm,Weight_kg,BMI,Blood_Pressure,Cholesterol,Glucose,...,Medication_Count,Hospital_Visits_Last_Year,Insurance_Type,Income_Level,City,Admission_Date,Discharge_Date,Length_of_Stay,Total_Hospital_Cost,Readmitted_30_Days
0,P0001,72,Male,Black,174,92,30.4,148/92,241,132,...,6,4,Medicare,Low,Baltimore,2026-01-04,2026-01-11,7,"$14,220.50",Yes
1,P0002,29,female,White,165,61,22.4,118/76,176,91,...,0,0,Private,Medium,Boston,2026-01-08,01/10/2026,2,"$3,180.00",No
2,P0003,64,MALE,Hispanic,68,98,32.9,145/88,263,142,...,5,3,Medicaid,Low,New Yrok,2026-01-11,2026-01-18,7,"$13,750.75",Yes
3,P0004,45,Female,Asian,160,77,30.1,132/84,198,126,...,2,1,Private,Medium,Chicago,2026-01-12,01/16/2026,4,"$7,930.20",No
4,P0005,83,male,Black,171,88,30.1,156/95,255,151,...,8,5,Medicare,Low,Detroit,2026-01-15,2026-01-25,10,"$21,400.90",Yes

In [15]:
df["Discharge_Date"] = pd.to_datetime(df["Discharge_Date"], format='mixed')

In [18]:
df.head()

,Patient_ID,Age,Gender,Race,Height_cm,Weight_kg,BMI,Blood_Pressure,Cholesterol,Glucose,...,Medication_Count,Hospital_Visits_Last_Year,Insurance_Type,Income_Level,City,Admission_Date,Discharge_Date,Length_of_Stay,Total_Hospital_Cost,Readmitted_30_Days
0,P0001,72,Male,Black,174,92,30.4,148/92,241,132,...,6,4,Medicare,Low,Baltimore,2026-01-04,2026-01-11,7,"$14,220.50",Yes
1,P0002,29,female,White,165,61,22.4,118/76,176,91,...,0,0,Private,Medium,Boston,2026-01-08,2026-01-10,2,"$3,180.00",No
2,P0003,64,MALE,Hispanic,68,98,32.9,145/88,263,142,...,5,3,Medicaid,Low,New Yrok,2026-01-11,2026-01-18,7,"$13,750.75",Yes
3,P0004,45,Female,Asian,160,77,30.1,132/84,198,126,...,2,1,Private,Medium,Chicago,2026-01-12,2026-01-16,4,"$7,930.20",No
4,P0005,83,male,Black,171,88,30.1,156/95,255,151,...,8,5,Medicare,Low,Detroit,2026-01-15,2026-01-25,10,"$21,400.90",Yes

In [20]:
df.corr

<bound method DataFrame.corr of    Patient_ID  Age  Gender      Race  Height_cm  Weight_kg   BMI  \
0       P0001   72    Male     Black        174         92  30.4
1       P0002   29  female     White        165         61  22.4
2       P0003   64    MALE  Hispanic         68         98  32.9
3       P0004   45  Female     Asian        160         77  30.1
4       P0005   83    male     Black        171         88  30.1
5       P0006   72    Male     Black        174         92  30.4
6       P0007   29  female     White        165         61  22.4
7       P0008   64    MALE  Hispanic         68         98  32.9
8       P0009   45  Female     Asian        160         77  30.1
9       P0010   83    male     Black        171         88  30.1
10      P0011   72    Male     Black        174         92  30.4
11      P0012   29  female     White        165         61  22.4
12      P0013   64    MALE  Hispanic         68         98  32.9
13      P0014   45  Female     Asian        160         77  30.1
14      P0015   83    male     Black        171         88  30.1
15      P0016   72    Male     Black        174         92  30.4
16      P0017   29  female     White        165         61  22.4
17      P0018   64    MALE  Hispanic         68         98  32.9
18      P0019   45  Female     Asian        160         77  30.1
19      P0020   83    male     Black        171         88  30.1
20      P0021   72    Male     Black        174         92  30.4
21      P0022   29  female     White        165         61  22.4
22      P0023   64    MALE  Hispanic         68         98  32.9
23      P0024   45  Female     Asian        160         77  30.1
24      P0025   83    male     Black        171         88  30.1
25      P0026   72    Male     Black        174         92  30.4
26      P0027   29  female     White        165         61  22.4
27      P0028   64    MALE  Hispanic         68         98  32.9
28      P0029   45  Female     Asian        160         77  30.1
29      P0030   83    male     Black        171         88  30.1
30      P0031   72    Male     Black        174         92  30.4
31      P0032   29  female     White        165         61  22.4
32      P0033   64    MALE  Hispanic         68         98  32.9
33      P0034   45  Female     Asian        160         77  30.1
34      P0035   83    male     Black        171         88  30.1
35      P0036   72    Male     Black        174         92  30.4
36      P0037   29  female     White        165         61  22.4
37      P0038   64    MALE  Hispanic         68         98  32.9
38      P0039   45  Female     Asian        160         77  30.1
39      P0040   83    male     Black        171         88  30.1
40      P0041   72    Male     Black        174         92  30.4
41      P0042   29  female     White        165         61  22.4
42      P0043   64    MALE  Hispanic         68         98  32.9
43      P0044   45  Female     Asian        160         77  30.1
44      P0045   83    male     Black        171         88  30.1
45      P0046   72    Male     Black        174         92  30.4
46      P0047   29  female     White        165         61  22.4
47      P0048   64    MALE  Hispanic         68         98  32.9
48      P0049   45  Female     Asian        160         77  30.1
49      P0050   83    male     Black        171         88  30.1

   Blood_Pressure  Cholesterol  Glucose  ...  Medication_Count  \
0          148/92          241      132  ...                 6
1          118/76          176       91  ...                 0
2          145/88          263      142  ...                 5
3          132/84          198      126  ...                 2
4          156/95          255      151  ...                 8
5          148/92          241      132  ...                 6
6          118/76          176       91  ...                 0
7          145/88          263      142  ...                 5
8          132/84          198      126  ...                 2
9          156/95          255      151  ...                 8
10         148/92          241      132  ...                 6
11         118/76          176       91  ...                 0
12         145/88          263      142  ...                 5
13         132/84          198      126  ...                 2
14         156/95          255      151  ...                 8
15         148/92          241      132  ...                 6
16         118/76          176       91  ...                 0
17         145/88          263      142  ...                 5
18         132/84          198      126  ...                 2
19         156/95          255      151  ...                 8
20         148/92          241      132  ...                 6
21         118/76          176       91  ...                 0
22         145/88          263      142  ...                 5
23         132/84          198      126  ...                 2
24         156/95          255      151  ...                 8
25         148/92          241      132  ...                 6
26         118/76          176       91  ...                 0
27         145/88          263      142  ...                 5
28         132/84          198      126  ...                 2
29         156/95          255      151  ...                 8
30         148/92          241      132  ...                 6
31         118/76          176       91  ...                 0
32         145/88          263      142  ...                 5
33         132/84          198      126  ...                 2
34         156/95          255      151  ...                 8
35         148/92          241      132  ...                 6
36         118/76          176       91  ...                 0
37         145/88          263      142  ...                 5
38         132/84          198      126  ...                 2
39         156/95          255      151  ...                 8
40         148/92          241      132  ...                 6
41         118/76          176       91  ...                 0
42         145/88          263      142  ...                 5
43         132/84          198      126  ...                 2
44         156/95          255      151  ...                 8
45         148/92          241      132  ...                 6
46         118/76          176       91  ...                 0
47         145/88          263      142  ...                 5
48         132/84          198      126  ...                 2
49         156/95          255      151  ...                 8

   Hospital_Visits_Last_Year Insurance_Type Income_Level         City  \
0                          4       Medicare          Low   Baltimore
1                          0        Private       Medium       Boston
2                          3       Medicaid          Low     New Yrok
3                          1        Private       Medium      Chicago
4                          5       Medicare          Low      Detroit
5                          4       Medicare          Low   Baltimore
6                          0        Private       Medium       Boston
7                          3       Medicaid          Low     New Yrok
8                          1        Private       Medium      Chicago
9                          5       Medicare          Low      Detroit
10                         4       Medicare          Low   Baltimore
11                         0        Private       Medium       Boston
12                         3       Medicaid          Low     New Yrok
13                         1        Private       Medium      Chicago
14                         5       Medicare          Low      Detroit
15                         4       Medicare          Low   Baltimore
16                         0        Private       Medium       Boston
17                         3       Medicaid          Low     New Yrok
18                         1        Private       Medium      Chicago
19                         5       Medicare          Low      Detroit
20                         4       Medicare          Low   Baltimore
21                         0        Private       Medium       Boston
22                         3       Medicaid          Low     New Yrok
23                         1        Private       Medium      Chicago
24                         5       Medicare          Low      Detroit
25                         4       Medicare          Low   Baltimore
26                         0        Private       Medium       Boston
27                         3       Medicaid          Low     New Yrok
28                         1        Private       Medium      Chicago
29                         5       Medicare          Low      Detroit
30                         4       Medicare          Low   Baltimore
31                         0        Private       Medium       Boston
32                         3       Medicaid          Low     New Yrok
33                         1        Private       Medium      Chicago
34                         5       Medicare          Low      Detroit
35                         4       Medicare          Low   Baltimore
36                         0        Private       Medium       Boston
37                         3       Medicaid          Low     New Yrok
38                         1        Private       Medium      Chicago
39                         5       Medicare          Low      Detroit
40                         4       Medicare          Low   Baltimore
41                         0        Private       Medium       Boston
42                         3       Medicaid          Low     New Yrok
43                         1        Private       Medium      Chicago
44                         5       Medicare          Low      Detroit
45                         4       Medicare          Low   Baltimore
46                         0        Private       Medium       Boston
47                         3       Medicaid          Low     New Yrok
48                         1        Private       Medium      Chicago
49                         5       Medicare          Low      Detroit

   Admission_Date Discharge_Date  Length_of_Stay  Total_Hospital_Cost  \
0      2026-01-04     2026-01-11               7           $14,220.50
1      2026-01-08     2026-01-10               2            $3,180.00
2      2026-01-11     2026-01-18               7           $13,750.75
3      2026-01-12     2026-01-16               4            $7,930.20
4      2026-01-15     2026-01-25              10           $21,400.90
5      2026-01-04     2026-01-11               7           $14,220.50
6      2026-01-08     2026-01-10               2            $3,180.00
7      2026-01-11     2026-01-18               7           $13,750.75
8      2026-01-12     2026-01-16               4            $7,930.20
9      2026-01-15     2026-01-25              10           $21,400.90
10     2026-01-04     2026-01-11               7           $14,220.50
11     2026-01-08     2026-01-10               2            $3,180.00
12     2026-01-11     2026-01-18               7           $13,750.75
13     2026-01-12     2026-01-16               4            $7,930.20
14     2026-01-15     2026-01-25              10           $21,400.90
15     2026-01-04     2026-01-11               7           $14,220.50
16     2026-01-08     2026-01-10               2            $3,180.00
17     2026-01-11     2026-01-18               7           $13,750.75
18     2026-01-12     2026-01-16               4            $7,930.20
19     2026-01-15     2026-01-25              10           $21,400.90
20     2026-01-04     2026-01-11               7           $14,220.50
21     2026-01-08     2026-01-10               2            $3,180.00
22     2026-01-11     2026-01-18               7           $13,750.75
23     2026-01-12     2026-01-16               4            $7,930.20
24     2026-01-15     2026-01-25              10           $21,400.90
25     2026-01-04     2026-01-11               7           $14,220.50
26     2026-01-08     2026-01-10               2            $3,180.00
27     2026-01-11     2026-01-18               7           $13,750.75
28     2026-01-12     2026-01-16               4            $7,930.20
29     2026-01-15     2026-01-25              10           $21,400.90
30     2026-01-04     2026-01-11               7           $14,220.50
31     2026-01-08     2026-01-10               2            $3,180.00
32     2026-01-11     2026-01-18               7           $13,750.75
33     2026-01-12     2026-01-16               4            $7,930.20
34     2026-01-15     2026-01-25              10           $21,400.90
35     2026-01-04     2026-01-11               7           $14,220.50
36     2026-01-08     2026-01-10               2            $3,180.00
37     2026-01-11     2026-01-18               7           $13,750.75
38     2026-01-12     2026-01-16               4            $7,930.20
39     2026-01-15     2026-01-25              10           $21,400.90
40     2026-01-04     2026-01-11               7           $14,220.50
41     2026-01-08     2026-01-10               2            $3,180.00
42     2026-01-11     2026-01-18               7           $13,750.75
43     2026-01-12     2026-01-16               4            $7,930.20
44     2026-01-15     2026-01-25              10           $21,400.90
45     2026-01-04     2026-01-11               7           $14,220.50
46     2026-01-08     2026-01-10               2            $3,180.00
47     2026-01-11     2026-01-18               7           $13,750.75
48     2026-01-12     2026-01-16               4            $7,930.20
49     2026-01-15     2026-01-25              10           $21,400.90

   Readmitted_30_Days
0                 Yes
1                  No
2                 Yes
3                  No
4                 Yes
5                 Yes
6                  No
7                 Yes
8                  No
9                 Yes
10                Yes
11                 No
12                Yes
13                 No
14                Yes
15                Yes
16                 No
17                Yes
18                 No
19                Yes
20                Yes
21                 No
22                Yes
23                 No
24                Yes
25                Yes
26                 No
27                Yes
28                 No
29                Yes
30                Yes
31                 No
32                Yes
33                 No
34                Yes
35                Yes
36                 No
37                Yes
38                 No
39                Yes
40                Yes
41                 No
42                Yes
43                 No
44                Yes
45                Yes
46                 No
47                Yes
48                 No
49                Yes

[50 rows x 27 columns]>

In [21]:
df["Gender"] = df["Gender"].str.title()

In [22]:
df.head()

,Patient_ID,Age,Gender,Race,Height_cm,Weight_kg,BMI,Blood_Pressure,Cholesterol,Glucose,...,Medication_Count,Hospital_Visits_Last_Year,Insurance_Type,Income_Level,City,Admission_Date,Discharge_Date,Length_of_Stay,Total_Hospital_Cost,Readmitted_30_Days
0,P0001,72,Male,Black,174,92,30.4,148/92,241,132,...,6,4,Medicare,Low,Baltimore,2026-01-04,2026-01-11,7,"$14,220.50",Yes
1,P0002,29,Female,White,165,61,22.4,118/76,176,91,...,0,0,Private,Medium,Boston,2026-01-08,2026-01-10,2,"$3,180.00",No
2,P0003,64,Male,Hispanic,68,98,32.9,145/88,263,142,...,5,3,Medicaid,Low,New Yrok,2026-01-11,2026-01-18,7,"$13,750.75",Yes
3,P0004,45,Female,Asian,160,77,30.1,132/84,198,126,...,2,1,Private,Medium,Chicago,2026-01-12,2026-01-16,4,"$7,930.20",No
4,P0005,83,Male,Black,171,88,30.1,156/95,255,151,...,8,5,Medicare,Low,Detroit,2026-01-15,2026-01-25,10,"$21,400.90",Yes

In [23]:
df["City"].unique()

array([' Baltimore ', 'Boston', 'New Yrok', 'Chicago', 'Detroit'],
      dtype=object)

In [24]:
df["City"] = df["City"].replace({
    "New Yrok": "New York"
})

In [25]:
df["City"].unique()

array([' Baltimore ', 'Boston', 'New York', 'Chicago', 'Detroit'],
      dtype=object)